--게시글 목록
SELECT * FROM NOTICES ORDER BY REGDATE DESC;

SELECT MAX(CODE) FROM NOTICEFILES;

SELECT MAX(CAST(CODE AS INT))+1 FROM Noticefiles;

--게시글 조회
SELECT * FROM NOTICES WHERE CODE = 135;

--현재 공지사항에서 가장 큰 CODE 얻기
SELECT NVL(MAX(TO_NUMBER(CODE)),0)+1 FROM NOTICES;
SELECT ISNULL(MAX (CAST (CODE AS INT)) ,0) + 1 FROM NoticeFiles;

--20개씩 나눈 레코드를 얻어오는 쿼리를 작성하시오
--1페이지, 2페이지
SELECT * FROM (SELECT * FROM NOTICES ORDER BY REGDATE DESC) 
--ROWNUM을 이용한 페이지 나누기
WHERE ROWNUM BETWEEN 1 AND 20 ;

INSERT INTO NOTICES(CODE,TITLE,WRITER,CONTENT,REGDATE,HIT) VALUES('132','eoot','hj','album',SYSDATE,0);

SELECT * FROM (SELECT ROWNUM NUM, N.* FROM (SELECT * FROM NOTICES ORDER BY REGDATE DESC) N )
WHERE NUM BETWEEN 2 AND 4 ;

SELECT N.* FROM
(
SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM, NOTICES.* 
FROM NOTICES 
) N
WHERE N.NUM BETWEEN 11 AND 20;

-- 이전 글(다음 글 같지만 실제 게시판을 생각해보면 이해할 수 있겠음)
SELECT * FROM NOTICES WHERE REGDATE > (SELECT REGDATE FROM NOTICES WHERE CODE='242')
ORDER BY REGDATE ASC;

-- TOP 1을 해주면 가장 위에 것만 셀렉해주지만, 굳이 여기서 안해주고 하나만 자바코드로 하나만 읽어오게 하면된다.
SELECT TOP 1 * FROM NOTICES WHERE REGDATE > (SELECT REGDATE FROM NOTICES WHERE CODE='242')
ORDER BY REGDATE ASC;

SELECT * FROM NOTICES WHERE REGDATE < (SELECT REGDATE FROM NOTICES WHERE CODE='242')
ORDER BY REGDATE DESC;

SELECT * FROM NOTICES ORDER BY REGDATE DESC;

select * from members;

SELECT COUNT(CODE) FROM NOTICES;

SELECT (ROW_NUMBER( ) OVER (ORDER BY REGDATE DESC)) NUM, NOTICES.* FROM NOTICES;